/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.user;

import controller.Controller;
import controller.UserBackendController;
import domain.Address;
import domain.AppUser;
import domain.Country;
import domain.UserCRUDType;
import java.awt.Color;
import java.lang.reflect.Field;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author Nikola
 */
public class JPanelUserAddressCRUD extends javax.swing.JPanel {

    private final AppUser appUser;
    private final UserCRUDType cRUDType;
    private boolean formSubmitetedOnce = false;
    private final String passwordPaterrn = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,}$";
    private final String emailPaterrn = "[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,64}";

    /**
     * Creates new form JPanelUserCRUD
     *
     * @param appUser
     * @param cRUDType
     */
    public JPanelUserAddressCRUD(AppUser appUser, UserCRUDType cRUDType) {
        initComponents();
        this.appUser = appUser == null ? new AppUser() : appUser;
        this.cRUDType = cRUDType;
        initCustomCompoents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldCountry = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldStreetNumber = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonSaveUser = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        CountryFieldErrorLabel = new javax.swing.JLabel();
        CityFieldErrorLabel = new javax.swing.JLabel();
        AddressFieldErrorLabel = new javax.swing.JLabel();
        StreetNumberFieldErrorLabel = new javax.swing.JLabel();
        jButtonSave = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Border Title Add/Edit/Read"));

        jLabel1.setText("Country");

        jTextFieldCountry.setName("FirstNameField"); // NOI18N
        jTextFieldCountry.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCountryKeyReleased(evt);
            }
        });

        jLabel2.setText("City");

        jTextFieldCity.setName("LastnameField"); // NOI18N
        jTextFieldCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCityKeyReleased(evt);
            }
        });

        jLabel3.setText("Address");

        jTextFieldAddress.setName("UsernameField"); // NOI18N
        jTextFieldAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldAddressKeyReleased(evt);
            }
        });

        jLabel4.setText("Street Number");

        jTextFieldStreetNumber.setName("EmailField"); // NOI18N
        jTextFieldStreetNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldStreetNumberKeyReleased(evt);
            }
        });

        jButtonSaveUser.setText("Next Step");
        jButtonSaveUser.setEnabled(false);
        jButtonSaveUser.setMaximumSize(new java.awt.Dimension(100, 25));
        jButtonSaveUser.setMinimumSize(new java.awt.Dimension(100, 25));
        jButtonSaveUser.setPreferredSize(new java.awt.Dimension(100, 25));
        jButtonSaveUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveUserActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.setMaximumSize(new java.awt.Dimension(100, 25));
        jButtonCancel.setMinimumSize(new java.awt.Dimension(100, 25));
        jButtonCancel.setPreferredSize(new java.awt.Dimension(100, 25));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        AddressFieldErrorLabel.setText(" ");

        jButtonSave.setText("Save User");
        jButtonSave.setMaximumSize(new java.awt.Dimension(100, 25));
        jButtonSave.setMinimumSize(new java.awt.Dimension(100, 25));
        jButtonSave.setPreferredSize(new java.awt.Dimension(100, 25));
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonBack.setText("Back");
        jButtonBack.setMaximumSize(new java.awt.Dimension(100, 25));
        jButtonBack.setMinimumSize(new java.awt.Dimension(100, 25));
        jButtonBack.setPreferredSize(new java.awt.Dimension(100, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldStreetNumber)
                            .addComponent(jTextFieldAddress)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCity)
                            .addComponent(jTextFieldCountry)))
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 113, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StreetNumberFieldErrorLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AddressFieldErrorLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CityFieldErrorLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CountryFieldErrorLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSaveUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CountryFieldErrorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CityFieldErrorLabel)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddressFieldErrorLabel)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldStreetNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StreetNumberFieldErrorLabel)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 285, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSaveUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        SwingUtilities.getWindowAncestor(this).setVisible(false);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonSaveUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveUserActionPerformed

    }//GEN-LAST:event_jButtonSaveUserActionPerformed

    private void jTextFieldCountryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCountryKeyReleased
        if (formSubmitetedOnce) {
            validateOneField(jTextFieldCountry);
        }
    }//GEN-LAST:event_jTextFieldCountryKeyReleased

    private void jTextFieldCityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCityKeyReleased
        if (formSubmitetedOnce) {
            validateOneField(jTextFieldCity);
        }
    }//GEN-LAST:event_jTextFieldCityKeyReleased

    private void jTextFieldAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAddressKeyReleased
        if (formSubmitetedOnce) {
            validateOneField(jTextFieldAddress);
        }
    }//GEN-LAST:event_jTextFieldAddressKeyReleased

    private void jTextFieldStreetNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldStreetNumberKeyReleased
        if (formSubmitetedOnce) {
            validateOneField(jTextFieldStreetNumber);
        }
    }//GEN-LAST:event_jTextFieldStreetNumberKeyReleased

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        formSubmitetedOnce = true;
        boolean formValid;
        try {
            formValid = validateAddress();
        } catch (NoSuchFieldException | IllegalArgumentException | IllegalAccessException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "System Error", JOptionPane.ERROR_MESSAGE);
//            JOptionPane.showMessageDialog(null, "System Error. Please contact your administator at \"Help Section\"", "System Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!formValid) {
//            JOptionPane.showMessageDialog(null, "Form is not valid! Please check all fields and submit form again.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Address address = appUser.getAddress() == null ? new Address() : appUser.getAddress();

        address.setCountry(new Country().setName(jTextFieldCountry.getText().trim()));
        address.setCity(jTextFieldCity.getText().trim());
        address.setPostalCode(jTextFieldAddress.getText().trim());
        address.setStreetNumber(jTextFieldStreetNumber.getText().trim());
        
                switch (cRUDType) {
            case Add:
            case Edit: {
                try {
                    UserBackendController.getController().saveAppUser(appUser);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, "System Error. " + ex.getMessage(), "System Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            break;
            default:
                JOptionPane.showMessageDialog(null, "System Error. This shouldnt have hapend", "System Error", JOptionPane.ERROR_MESSAGE);
        }

        JOptionPane.showMessageDialog(null, "User saved successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_jButtonSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressFieldErrorLabel;
    private javax.swing.JLabel CityFieldErrorLabel;
    private javax.swing.JLabel CountryFieldErrorLabel;
    private javax.swing.JLabel StreetNumberFieldErrorLabel;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSaveUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldCity;
    private javax.swing.JTextField jTextFieldCountry;
    private javax.swing.JTextField jTextFieldStreetNumber;
    // End of variables declaration//GEN-END:variables

    private boolean validateAddress() throws NoSuchFieldException, IllegalArgumentException, IllegalAccessException {
        boolean formValid = true;

        if (!validateIsEmpty(jTextFieldCountry, jTextFieldCity, jTextFieldAddress, jTextFieldStreetNumber)) {
            JOptionPane.showMessageDialog(this, "All fields on form are mentatory!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return formValid;
    }

    private boolean validateIsEmpty(JTextField... fields) throws NoSuchFieldException, IllegalArgumentException, IllegalAccessException {
        boolean fieldsNotEmpty = true;
        for (JTextField field : fields) {
            if (field.getText().isEmpty()) {
                fieldsNotEmpty = false;
                Field fieldError = this.getClass().getDeclaredField(field.getName() + "ErrorLabel");
                JLabel errorLab = (JLabel) fieldError.get(this);
                errorLab.setText("Please fill this field!");
                errorLab.setForeground(Color.red);
            }
        }

        return fieldsNotEmpty;
    }

    private void validateOneField(JTextField field) {
        try {
            Field fieldError = this.getClass().getDeclaredField(field.getName() + "ErrorLabel");
            JLabel errorLab = (JLabel) fieldError.get(this);

            if (field.getText().isEmpty()) {
                errorLab.setText("Please fill this field!");
                errorLab.setForeground(Color.red);
            } else {
                errorLab.setText(null);
            }

        } catch (NoSuchFieldException | SecurityException | IllegalArgumentException | IllegalAccessException ex) {
            System.out.println(ex.getMessage());
        }
    }

    private void initCustomCompoents() {
        switch (cRUDType) {
            case Add:
                break;
            case View:
                jButtonSaveUser.setEnabled(false);
                Arrays.asList(jTextFieldCountry, jTextFieldCity, jTextFieldAddress, jTextFieldStreetNumber)
                        .stream()
                        .forEach((field) -> field.setEditable(false));
            case Edit:
                formSubmitetedOnce = true;
                setUpFields();
                break;
        }
    }

    private void setUpFields() {
        jTextFieldCountry.setText(appUser.getFirstname());
        jTextFieldCity.setText(appUser.getLastname());
        jTextFieldAddress.setText(appUser.getUsername());
        jTextFieldStreetNumber.setText(appUser.getEmail());
    }
}
