/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.user;

import constant.ConstantMessages;
import controller.UserBackendController;
import domain.user.AppUser;
import domain.PaginationOption;
import domain.user.StatusType;
import domain.UserCRUDType;
import domain.user.Country;
import java.awt.Dialog;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.util.Arrays;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.UserTableModel;
import view.user.task.JPanelAddTask;

/**
 *
 * @author Filip
 */
public class JPanelUserAll extends javax.swing.JPanel {

    private int page = 1;
    private int offset = 10;
    private int maxPages = 1;

    /**
     * Creates new form JPanelUserAll
     */
    public JPanelUserAll() {
        initComponents();
        initCustomComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldHint = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jCheckBoxRoleUser = new javax.swing.JCheckBox();
        jCheckBoxRoleAdmin = new javax.swing.JCheckBox();
        jCheckBoxRoleSuperAdmin = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jButtonBanUser = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxChangeStatusQuick = new javax.swing.JComboBox<>();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jButtonAddTaskQuick = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldDateFilterFrom = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldDateFilterTo = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jCheckBoxStatusActivate = new javax.swing.JCheckBox();
        jCheckBoxStatusLocked = new javax.swing.JCheckBox();
        jCheckBoxStatusPending = new javax.swing.JCheckBox();
        jCheckBoxBanedFilter = new javax.swing.JCheckBox();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jButtonCountryFilter = new javax.swing.JButton();
        jButtonCityFilter = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButtonResetAllFilters = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButtonFirstPage = new javax.swing.JButton();
        jButtonPreviousPage = new javax.swing.JButton();
        jTextFieldCurrentPage = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldMaxPage = new javax.swing.JTextField();
        jButtonNextPage = new javax.swing.JButton();
        jButtonLastPage = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("List of All Users"));
        setMaximumSize(new java.awt.Dimension(958, 684));

        jLabel1.setText("Filter User:");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));
        jPanel1.setMaximumSize(new java.awt.Dimension(924, 161));
        jPanel1.setMinimumSize(new java.awt.Dimension(924, 161));
        jPanel1.setName(""); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Edit User"));

        jButton2.setText("Edit User");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("You will be open a new tab to edit user.");

        jButton4.setText("View User");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Quick Options\n"));

        jCheckBoxRoleUser.setText("App User");
        jCheckBoxRoleUser.setEnabled(false);

        jCheckBoxRoleAdmin.setText("Admin");
        jCheckBoxRoleAdmin.setEnabled(false);

        jCheckBoxRoleSuperAdmin.setText("Super Admin");
        jCheckBoxRoleSuperAdmin.setEnabled(false);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel3.setText("You can change state of user here.");

        jButtonBanUser.setText("Ban user");
        jButtonBanUser.setEnabled(false);
        jButtonBanUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBanUserActionPerformed(evt);
            }
        });

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel4.setText("Execute ban operation on user.");

        jComboBoxChangeStatusQuick.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Pending", "Locked" }));
        jComboBoxChangeStatusQuick.setEnabled(false);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel10.setText("Add tast for selected user");

        jButtonAddTaskQuick.setText("Add Task");
        jButtonAddTaskQuick.setEnabled(false);
        jButtonAddTaskQuick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddTaskQuickActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxRoleUser)
                    .addComponent(jCheckBoxRoleAdmin)
                    .addComponent(jCheckBoxRoleSuperAdmin))
                .addGap(41, 41, 41)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxChangeStatusQuick, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jButtonAddTaskQuick))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jButtonBanUser))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAddTaskQuick))
                    .addComponent(jSeparator6)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jCheckBoxRoleUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxRoleAdmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxRoleSuperAdmin)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBanUser, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxChangeStatusQuick, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Advanced Search "));

        jLabel6.setText("Activate user (yyyy.mm.dd)");

        jTextFieldDateFilterFrom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldDateFilterFromKeyReleased(evt);
            }
        });

        jLabel7.setText("-");

        jTextFieldDateFilterTo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldDateFilterToKeyReleased(evt);
            }
        });

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel8.setText("User Status");

        jCheckBoxStatusActivate.setText("Activate");
        jCheckBoxStatusActivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxStatusActivateActionPerformed(evt);
            }
        });

        jCheckBoxStatusLocked.setText("Locked");
        jCheckBoxStatusLocked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxStatusLockedActionPerformed(evt);
            }
        });

        jCheckBoxStatusPending.setText("Pending");
        jCheckBoxStatusPending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxStatusPendingActionPerformed(evt);
            }
        });

        jCheckBoxBanedFilter.setText("Baned");
        jCheckBoxBanedFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxBanedFilterActionPerformed(evt);
            }
        });

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel9.setText("Advanced Filters");

        jButtonCountryFilter.setText("Country");
        jButtonCountryFilter.setMaximumSize(new java.awt.Dimension(80, 25));
        jButtonCountryFilter.setMinimumSize(new java.awt.Dimension(80, 25));
        jButtonCountryFilter.setPreferredSize(new java.awt.Dimension(80, 25));
        jButtonCountryFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCountryFilterActionPerformed(evt);
            }
        });

        jButtonCityFilter.setText("City");
        jButtonCityFilter.setEnabled(false);
        jButtonCityFilter.setMaximumSize(new java.awt.Dimension(80, 25));
        jButtonCityFilter.setMinimumSize(new java.awt.Dimension(80, 25));
        jButtonCityFilter.setPreferredSize(new java.awt.Dimension(80, 25));

        jButton11.setText("Filter");
        jButton11.setEnabled(false);
        jButton11.setMaximumSize(new java.awt.Dimension(80, 25));
        jButton11.setMinimumSize(new java.awt.Dimension(80, 25));
        jButton11.setPreferredSize(new java.awt.Dimension(80, 25));

        jButtonResetAllFilters.setText("Reset All Filters");
        jButtonResetAllFilters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetAllFiltersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextFieldDateFilterFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDateFilterTo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jCheckBoxStatusActivate)
                        .addGap(42, 42, 42)
                        .addComponent(jCheckBoxBanedFilter))
                    .addComponent(jCheckBoxStatusLocked)
                    .addComponent(jCheckBoxStatusPending))
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButtonCountryFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCityFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(285, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonResetAllFilters, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCountryFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCityFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonResetAllFilters))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextFieldDateFilterFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7)
                                            .addComponent(jTextFieldDateFilterTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jCheckBoxStatusActivate)
                                            .addComponent(jCheckBoxBanedFilter))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxStatusLocked)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxStatusPending)
                                .addGap(0, 39, Short.MAX_VALUE))))
                    .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );

        jButtonFirstPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/image/levo-dupla.png"))); // NOI18N
        jButtonFirstPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFirstPageActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonFirstPage);

        jButtonPreviousPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/image/levo-jedna.png"))); // NOI18N
        jButtonPreviousPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreviousPageActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonPreviousPage);

        jTextFieldCurrentPage.setMaximumSize(new java.awt.Dimension(30, 25));
        jTextFieldCurrentPage.setMinimumSize(new java.awt.Dimension(30, 25));
        jTextFieldCurrentPage.setPreferredSize(new java.awt.Dimension(30, 25));
        jPanel5.add(jTextFieldCurrentPage);

        jLabel5.setText(" - ");
        jPanel5.add(jLabel5);

        jTextFieldMaxPage.setEditable(false);
        jTextFieldMaxPage.setMaximumSize(new java.awt.Dimension(30, 25));
        jTextFieldMaxPage.setMinimumSize(new java.awt.Dimension(30, 25));
        jTextFieldMaxPage.setPreferredSize(new java.awt.Dimension(30, 25));
        jPanel5.add(jTextFieldMaxPage);

        jButtonNextPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/image/desno-jedna.png"))); // NOI18N
        jButtonNextPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextPageActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonNextPage);

        jButtonLastPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/image/desno-dupla.png"))); // NOI18N
        jButtonLastPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLastPageActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonLastPage);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldHint)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldHint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBanUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBanUserActionPerformed
        int selectedIndex = jTable1.getSelectedRow();
        if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(null, "Please select user!!!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        JDialog dialog = new JDialog(null, "Ban Confrmation", Dialog.ModalityType.APPLICATION_MODAL);
        JPanel panel = new JPanelBanConfirmation(((UserTableModel) jTable1.getModel()).getUserAt(selectedIndex));
        dialog.add(panel);
        dialog.setResizable(false);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButtonBanUserActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int selectedIndex = jTable1.getSelectedRow();

        if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(null, "Please select user!!!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        JDialog dialog = new JDialog(null, "User Details", Dialog.ModalityType.APPLICATION_MODAL);
        JPanel panel = new JPanelUserCrud(((UserTableModel) jTable1.getModel()).getUserAt(selectedIndex), UserCRUDType.VIEW);
        dialog.add(panel);
        dialog.setResizable(false);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selectedIndex = jTable1.getSelectedRow();

        if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(null, "Please select user!!!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        JDialog dialog = new JDialog(null, "User Details", Dialog.ModalityType.APPLICATION_MODAL);
        JPanel panel = new JPanelUserCrud(((UserTableModel) jTable1.getModel()).getUserAt(selectedIndex), UserCRUDType.EDIT);
        dialog.add(panel);
        dialog.setResizable(false);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int selectedIndex = jTable1.getSelectedRow();
        if (selectedIndex < 0) {
            return;
        }
        AppUser appUser = ((UserTableModel) jTable1.getModel()).getUserAt(selectedIndex);

        activeButtonsForUser(appUser);

        if (evt.getClickCount() == 2) {
            JDialog dialog = new JDialog(null, "User Details", Dialog.ModalityType.APPLICATION_MODAL);
            JPanel panel = new JPanelUserCrud(appUser, UserCRUDType.VIEW);
            dialog.add(panel);
            dialog.setResizable(false);
            dialog.pack();
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonLastPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLastPageActionPerformed
        changePaginationPage(PaginationOption.LastPage);
    }//GEN-LAST:event_jButtonLastPageActionPerformed

    private void jButtonNextPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextPageActionPerformed
        changePaginationPage(PaginationOption.NextPage);
    }//GEN-LAST:event_jButtonNextPageActionPerformed

    private void jButtonPreviousPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviousPageActionPerformed
        changePaginationPage(PaginationOption.PreviousPage);
    }//GEN-LAST:event_jButtonPreviousPageActionPerformed

    private void jButtonFirstPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFirstPageActionPerformed
        changePaginationPage(PaginationOption.FirstPage);
    }//GEN-LAST:event_jButtonFirstPageActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        UserTableModel tableModel = (UserTableModel) jTable1.getModel();
        maxPages = tableModel.filterByHint(jTextFieldHint.getText().trim(), offset);
        page = 1;

        jTextFieldMaxPage.setText("" + maxPages);
        jTextFieldCurrentPage.setText("" + page);
        disableQuickButtonsForUser();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonResetAllFiltersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetAllFiltersActionPerformed
        UserTableModel tableModel = (UserTableModel) jTable1.getModel();
        maxPages = tableModel.resetAllFilters(offset);
        page = 1;

        jTextFieldMaxPage.setText("" + maxPages);
        jTextFieldCurrentPage.setText("" + page);
        jTextFieldHint.setText(null);
        jTextFieldDateFilterFrom.setText(null);
        jTextFieldDateFilterTo.setText(null);

        Arrays.asList(jCheckBoxBanedFilter, jCheckBoxStatusActivate, jCheckBoxStatusPending, jCheckBoxStatusLocked)
                .stream()
                .forEach((cb) -> cb.setSelected(false));
        disableQuickButtonsForUser();
    }//GEN-LAST:event_jButtonResetAllFiltersActionPerformed

    private void jCheckBoxStatusActivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxStatusActivateActionPerformed
        UserTableModel tableModel = (UserTableModel) jTable1.getModel();
        maxPages = jCheckBoxStatusActivate.isSelected() ? tableModel.addStatusFilter(StatusType.ACTIVE, offset) : tableModel.removeStatusFilter(StatusType.ACTIVE, offset);
        page = 1;

        jTextFieldMaxPage.setText("" + maxPages);
        jTextFieldCurrentPage.setText("" + page);
        disableQuickButtonsForUser();
    }//GEN-LAST:event_jCheckBoxStatusActivateActionPerformed

    private void jCheckBoxStatusLockedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxStatusLockedActionPerformed
        UserTableModel tableModel = (UserTableModel) jTable1.getModel();
        maxPages = jCheckBoxStatusLocked.isSelected() ? tableModel.addStatusFilter(StatusType.LOCKED, offset) : tableModel.removeStatusFilter(StatusType.LOCKED, offset);
        page = 1;

        jTextFieldMaxPage.setText("" + maxPages);
        jTextFieldCurrentPage.setText("" + page);
        disableQuickButtonsForUser();
    }//GEN-LAST:event_jCheckBoxStatusLockedActionPerformed

    private void jCheckBoxStatusPendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxStatusPendingActionPerformed
        UserTableModel tableModel = (UserTableModel) jTable1.getModel();
        maxPages = jCheckBoxStatusPending.isSelected() ? tableModel.addStatusFilter(StatusType.PENDING, offset) : tableModel.removeStatusFilter(StatusType.PENDING, offset);
        page = 1;

        jTextFieldMaxPage.setText("" + maxPages);
        jTextFieldCurrentPage.setText("" + page);
        disableQuickButtonsForUser();
    }//GEN-LAST:event_jCheckBoxStatusPendingActionPerformed

    private void jCheckBoxBanedFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxBanedFilterActionPerformed
        UserTableModel tableModel = (UserTableModel) jTable1.getModel();
        maxPages = tableModel.addBanedFilter(jCheckBoxBanedFilter.isSelected(), offset);
        page = 1;

        jTextFieldMaxPage.setText("" + maxPages);
        jTextFieldCurrentPage.setText("" + page);
        disableQuickButtonsForUser();
    }//GEN-LAST:event_jCheckBoxBanedFilterActionPerformed

    private void jButtonAddTaskQuickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddTaskQuickActionPerformed
        int selectedIndex = jTable1.getSelectedRow();
        if (selectedIndex < 0) {
            JOptionPane.showMessageDialog(null, "Please select user to manage their tasks!", ConstantMessages.ERROR_MSG_TITLE, JOptionPane.ERROR_MESSAGE);
            return;
        }

        JDialog dialog = new JDialog(null, "User Details", Dialog.ModalityType.APPLICATION_MODAL);
        JPanel panel = new JPanelAddTask(((UserTableModel) jTable1.getModel()).getUserAt(selectedIndex));
        dialog.add(panel);
        dialog.setResizable(false);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButtonAddTaskQuickActionPerformed

    private void jButtonCountryFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCountryFilterActionPerformed
        UserTableModel tableModel = (UserTableModel) jTable1.getModel();
        JDialog dialog = new JDialog(null, "Country Filter", Dialog.ModalityType.APPLICATION_MODAL);
        JPanel panel = new JPanelFilterCountry(this, tableModel.getCountryFilter());
        dialog.add(panel);
        dialog.setResizable(false);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButtonCountryFilterActionPerformed

    private void jTextFieldDateFilterFromKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDateFilterFromKeyReleased
        UserTableModel tableModel = (UserTableModel) jTable1.getModel();
        try {
            LocalDate dateFrom = LocalDate.parse(jTextFieldDateFilterFrom.getText().trim(), controller.Controller.getController().formatter);
            maxPages = tableModel.addDateFromFilter(dateFrom, offset);
        } catch (DateTimeParseException ex) {
            maxPages = tableModel.removeDateFromFilter(offset);
        }

        jTextFieldMaxPage.setText("" + maxPages);
        jTextFieldCurrentPage.setText("" + page);
        disableQuickButtonsForUser();
    }//GEN-LAST:event_jTextFieldDateFilterFromKeyReleased

    private void jTextFieldDateFilterToKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDateFilterToKeyReleased
        UserTableModel tableModel = (UserTableModel) jTable1.getModel();
        try {
            LocalDate dateTo = LocalDate.parse(jTextFieldDateFilterTo.getText().trim(), controller.Controller.getController().formatter);
            maxPages = tableModel.addDateToFilter(dateTo, offset);
        } catch (DateTimeParseException ex) {
            maxPages = tableModel.removeDateToFilter(offset);
        }

        jTextFieldMaxPage.setText("" + maxPages);
        jTextFieldCurrentPage.setText("" + page);
        disableQuickButtonsForUser();
    }//GEN-LAST:event_jTextFieldDateFilterToKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonAddTaskQuick;
    private javax.swing.JButton jButtonBanUser;
    private javax.swing.JButton jButtonCityFilter;
    private javax.swing.JButton jButtonCountryFilter;
    private javax.swing.JButton jButtonFirstPage;
    private javax.swing.JButton jButtonLastPage;
    private javax.swing.JButton jButtonNextPage;
    private javax.swing.JButton jButtonPreviousPage;
    private javax.swing.JButton jButtonResetAllFilters;
    private javax.swing.JCheckBox jCheckBoxBanedFilter;
    private javax.swing.JCheckBox jCheckBoxRoleAdmin;
    private javax.swing.JCheckBox jCheckBoxRoleSuperAdmin;
    private javax.swing.JCheckBox jCheckBoxRoleUser;
    private javax.swing.JCheckBox jCheckBoxStatusActivate;
    private javax.swing.JCheckBox jCheckBoxStatusLocked;
    private javax.swing.JCheckBox jCheckBoxStatusPending;
    private javax.swing.JComboBox<String> jComboBoxChangeStatusQuick;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCurrentPage;
    private javax.swing.JTextField jTextFieldDateFilterFrom;
    private javax.swing.JTextField jTextFieldDateFilterTo;
    private javax.swing.JTextField jTextFieldHint;
    private javax.swing.JTextField jTextFieldMaxPage;
    // End of variables declaration//GEN-END:variables

    private void initCustomComponents() {
        List<AppUser> userList;
        try {
            userList = UserBackendController.getController().getAllUsersFromDB();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ConstantMessages.SYSTEM_ERROR_MSG, constant.ConstantMessages.ERROR_MSG_TITLE, JOptionPane.ERROR_MESSAGE);
            return;
        }

        jTable1.setModel(new UserTableModel(userList, offset));
        maxPages = (int) Math.ceil(userList.size() / (double) (offset));

        jTextFieldMaxPage.setText("" + maxPages);
        jTextFieldCurrentPage.setText("" + page);
    }

    void setCountryFilter(List<Country> filteredCountries) {
        UserTableModel tableModel = (UserTableModel) jTable1.getModel();
        maxPages = tableModel.addCountryFilter(filteredCountries, offset);
        page = 1;

        jTextFieldMaxPage.setText("" + maxPages);
        jTextFieldCurrentPage.setText("" + page);
        disableQuickButtonsForUser();
    }

    private void activeButtonsForUser(AppUser appUser) {
        jCheckBoxRoleSuperAdmin.setSelected(false);
        jCheckBoxRoleAdmin.setSelected(false);
        jCheckBoxRoleUser.setSelected(false);
        jComboBoxChangeStatusQuick.setEnabled(true);
        jButtonAddTaskQuick.setEnabled(true);
        jButtonBanUser.setEnabled(!appUser.isBaned());
        jCheckBoxRoleUser.setEnabled(true);
        jCheckBoxRoleAdmin.setEnabled(true);
        jCheckBoxRoleSuperAdmin.setEnabled(true);

        switch (appUser.getTitle()) {
            case ROLE_SUPERADMIN:
                jCheckBoxRoleSuperAdmin.setSelected(true);
            case ROLE_ADMIN:
                jCheckBoxRoleAdmin.setSelected(true);
            case ROLE_USER:
                jCheckBoxRoleUser.setSelected(true);
        }
        switch (appUser.getStatus()) {
            case ACTIVE:
                jComboBoxChangeStatusQuick.setSelectedItem("Active");
                break;
            case LOCKED:
                jComboBoxChangeStatusQuick.setSelectedItem("Locked");
                break;
            case PENDING:
                jComboBoxChangeStatusQuick.setSelectedItem("Pending");
                break;
        }
    }

    private void disableQuickButtonsForUser() {
        jCheckBoxRoleSuperAdmin.setSelected(false);
        jCheckBoxRoleAdmin.setSelected(false);
        jCheckBoxRoleUser.setSelected(false);
        jComboBoxChangeStatusQuick.setEnabled(false);
        jButtonAddTaskQuick.setEnabled(false);
        jButtonBanUser.setEnabled(false);
        jCheckBoxRoleUser.setEnabled(false);
        jCheckBoxRoleAdmin.setEnabled(false);
        jCheckBoxRoleSuperAdmin.setEnabled(false);
    }

    private void changePaginationPage(PaginationOption operation) {
        int currentPage;

        try {
            currentPage = Integer.parseInt(jTextFieldCurrentPage.getText());
        } catch (NumberFormatException exception) {
            jTextFieldCurrentPage.setText("" + page);
            return;
        }

        if (currentPage < 1 || currentPage > maxPages) {
            jTextFieldCurrentPage.setText("" + page);
            return;
        }

        switch (operation) {
            case FirstPage:
                currentPage = 1;
                break;
            case PreviousPage:
                currentPage = page == 1 ? 1 : page - 1;
                break;
            case NextPage:
                currentPage = page == maxPages ? maxPages : page + 1;
                break;
            case LastPage:
                currentPage = maxPages;
                break;
        }

        if (page == currentPage) {
            return;
        }

        page = currentPage;

        UserTableModel tableModel = (UserTableModel) jTable1.getModel();
        tableModel.changePage(page, offset);

        jTextFieldCurrentPage.setText("" + page);
        disableQuickButtonsForUser();
    }

}
